<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="0" tests="6" failures="6">
  <testsuite name="Root Suite" timestamp="2020-06-02T17:37:41" tests="0" failures="0" time="0">
  </testsuite>
  <testsuite name="Ask Question Community" timestamp="2020-06-02T17:37:41" tests="0" failures="0" time="0">
  </testsuite>
  <testsuite name="in mobile" timestamp="2020-06-02T17:37:41" tests="2" failures="2" time="0">
    <testcase name="Ask Question Community in mobile should ask a question" time="0" classname="should ask a question">
      <failure message="Timed out retrying: cy.wait() timed out waiting 30000ms for the 1st response to the route: &apos;postUuidActions&apos;. No response ever occurred." type="CypressError"><![CDATA[CypressError: Timed out retrying: cy.wait() timed out waiting 30000ms for the 1st response to the route: 'postUuidActions'. No response ever occurred.
    at Object.cypressErr (http://www.lvh.me/__cypress/runner/cypress_runner.js:105262:11)
    at Object.throwErr (http://www.lvh.me/__cypress/runner/cypress_runner.js:105217:18)
    at Object.throwErrByPath (http://www.lvh.me/__cypress/runner/cypress_runner.js:105249:17)
    at Object.retry (http://www.lvh.me/__cypress/runner/cypress_runner.js:96526:16)
    at checkForXhr (http://www.lvh.me/__cypress/runner/cypress_runner.js:92939:17)
    at http://www.lvh.me/__cypress/runner/cypress_runner.js:92940:28
    at tryCatcher (http://www.lvh.me/__cypress/runner/cypress_runner.js:139407:23)
    at Function.Promise.attempt.Promise.try (http://www.lvh.me/__cypress/runner/cypress_runner.js:136682:29)
    at tryFn (http://www.lvh.me/__cypress/runner/cypress_runner.js:96984:21)
    at whenStable (http://www.lvh.me/__cypress/runner/cypress_runner.js:97019:12)
    at http://www.lvh.me/__cypress/runner/cypress_runner.js:96569:16
    at tryCatcher (http://www.lvh.me/__cypress/runner/cypress_runner.js:139407:23)
    at Promise._settlePromiseFromHandler (http://www.lvh.me/__cypress/runner/cypress_runner.js:137343:31)
    at Promise._settlePromise (http://www.lvh.me/__cypress/runner/cypress_runner.js:137400:18)
    at Promise._settlePromise0 (http://www.lvh.me/__cypress/runner/cypress_runner.js:137445:10)
    at Promise._settlePromises (http://www.lvh.me/__cypress/runner/cypress_runner.js:137524:18)]]></failure>
    </testcase>
    <testcase name="Ask Question Community in mobile should leave an answer" time="0" classname="should leave an answer">
      <failure message="Timed out retrying: cy.wait() timed out waiting 30000ms for the 1st response to the route: &apos;postUuidActions&apos;. No response ever occurred." type="CypressError"><![CDATA[CypressError: Timed out retrying: cy.wait() timed out waiting 30000ms for the 1st response to the route: 'postUuidActions'. No response ever occurred.
    at Object.cypressErr (http://www.lvh.me/__cypress/runner/cypress_runner.js:105262:11)
    at Object.throwErr (http://www.lvh.me/__cypress/runner/cypress_runner.js:105217:18)
    at Object.throwErrByPath (http://www.lvh.me/__cypress/runner/cypress_runner.js:105249:17)
    at Object.retry (http://www.lvh.me/__cypress/runner/cypress_runner.js:96526:16)
    at checkForXhr (http://www.lvh.me/__cypress/runner/cypress_runner.js:92939:17)
    at http://www.lvh.me/__cypress/runner/cypress_runner.js:92940:28
    at tryCatcher (http://www.lvh.me/__cypress/runner/cypress_runner.js:139407:23)
    at Function.Promise.attempt.Promise.try (http://www.lvh.me/__cypress/runner/cypress_runner.js:136682:29)
    at tryFn (http://www.lvh.me/__cypress/runner/cypress_runner.js:96984:21)
    at whenStable (http://www.lvh.me/__cypress/runner/cypress_runner.js:97019:12)
    at http://www.lvh.me/__cypress/runner/cypress_runner.js:96569:16
    at tryCatcher (http://www.lvh.me/__cypress/runner/cypress_runner.js:139407:23)
    at Promise._settlePromiseFromHandler (http://www.lvh.me/__cypress/runner/cypress_runner.js:137343:31)
    at Promise._settlePromise (http://www.lvh.me/__cypress/runner/cypress_runner.js:137400:18)
    at Promise._settlePromise0 (http://www.lvh.me/__cypress/runner/cypress_runner.js:137445:10)
    at Promise._settlePromises (http://www.lvh.me/__cypress/runner/cypress_runner.js:137524:18)]]></failure>
    </testcase>
  </testsuite>
  <testsuite name="in tablet" timestamp="2020-06-02T17:38:47" tests="2" failures="2" time="0">
    <testcase name="Ask Question Community in tablet should ask a question" time="0" classname="should ask a question">
      <failure message="Timed out retrying: cy.wait() timed out waiting 30000ms for the 1st response to the route: &apos;postUuidActions&apos;. No response ever occurred." type="CypressError"><![CDATA[CypressError: Timed out retrying: cy.wait() timed out waiting 30000ms for the 1st response to the route: 'postUuidActions'. No response ever occurred.
    at Object.cypressErr (http://www.lvh.me/__cypress/runner/cypress_runner.js:105262:11)
    at Object.throwErr (http://www.lvh.me/__cypress/runner/cypress_runner.js:105217:18)
    at Object.throwErrByPath (http://www.lvh.me/__cypress/runner/cypress_runner.js:105249:17)
    at Object.retry (http://www.lvh.me/__cypress/runner/cypress_runner.js:96526:16)
    at checkForXhr (http://www.lvh.me/__cypress/runner/cypress_runner.js:92939:17)
    at http://www.lvh.me/__cypress/runner/cypress_runner.js:92940:28
    at tryCatcher (http://www.lvh.me/__cypress/runner/cypress_runner.js:139407:23)
    at Function.Promise.attempt.Promise.try (http://www.lvh.me/__cypress/runner/cypress_runner.js:136682:29)
    at tryFn (http://www.lvh.me/__cypress/runner/cypress_runner.js:96984:21)
    at whenStable (http://www.lvh.me/__cypress/runner/cypress_runner.js:97019:12)
    at http://www.lvh.me/__cypress/runner/cypress_runner.js:96569:16
    at tryCatcher (http://www.lvh.me/__cypress/runner/cypress_runner.js:139407:23)
    at Promise._settlePromiseFromHandler (http://www.lvh.me/__cypress/runner/cypress_runner.js:137343:31)
    at Promise._settlePromise (http://www.lvh.me/__cypress/runner/cypress_runner.js:137400:18)
    at Promise._settlePromise0 (http://www.lvh.me/__cypress/runner/cypress_runner.js:137445:10)
    at Promise._settlePromises (http://www.lvh.me/__cypress/runner/cypress_runner.js:137524:18)]]></failure>
    </testcase>
    <testcase name="Ask Question Community in tablet should leave an answer" time="0" classname="should leave an answer">
      <failure message="Timed out retrying: cy.wait() timed out waiting 30000ms for the 1st response to the route: &apos;postUuidActions&apos;. No response ever occurred." type="CypressError"><![CDATA[CypressError: Timed out retrying: cy.wait() timed out waiting 30000ms for the 1st response to the route: 'postUuidActions'. No response ever occurred.
    at Object.cypressErr (http://www.lvh.me/__cypress/runner/cypress_runner.js:105262:11)
    at Object.throwErr (http://www.lvh.me/__cypress/runner/cypress_runner.js:105217:18)
    at Object.throwErrByPath (http://www.lvh.me/__cypress/runner/cypress_runner.js:105249:17)
    at Object.retry (http://www.lvh.me/__cypress/runner/cypress_runner.js:96526:16)
    at checkForXhr (http://www.lvh.me/__cypress/runner/cypress_runner.js:92939:17)
    at http://www.lvh.me/__cypress/runner/cypress_runner.js:92940:28
    at tryCatcher (http://www.lvh.me/__cypress/runner/cypress_runner.js:139407:23)
    at Function.Promise.attempt.Promise.try (http://www.lvh.me/__cypress/runner/cypress_runner.js:136682:29)
    at tryFn (http://www.lvh.me/__cypress/runner/cypress_runner.js:96984:21)
    at whenStable (http://www.lvh.me/__cypress/runner/cypress_runner.js:97019:12)
    at http://www.lvh.me/__cypress/runner/cypress_runner.js:96569:16
    at tryCatcher (http://www.lvh.me/__cypress/runner/cypress_runner.js:139407:23)
    at Promise._settlePromiseFromHandler (http://www.lvh.me/__cypress/runner/cypress_runner.js:137343:31)
    at Promise._settlePromise (http://www.lvh.me/__cypress/runner/cypress_runner.js:137400:18)
    at Promise._settlePromise0 (http://www.lvh.me/__cypress/runner/cypress_runner.js:137445:10)
    at Promise._settlePromises (http://www.lvh.me/__cypress/runner/cypress_runner.js:137524:18)]]></failure>
    </testcase>
  </testsuite>
  <testsuite name="in laptop" timestamp="2020-06-02T17:39:54" tests="2" failures="2" time="0">
    <testcase name="Ask Question Community in laptop should ask a question" time="0" classname="should ask a question">
      <failure message="Timed out retrying: cy.wait() timed out waiting 30000ms for the 1st response to the route: &apos;postUuidActions&apos;. No response ever occurred." type="CypressError"><![CDATA[CypressError: Timed out retrying: cy.wait() timed out waiting 30000ms for the 1st response to the route: 'postUuidActions'. No response ever occurred.
    at Object.cypressErr (http://www.lvh.me/__cypress/runner/cypress_runner.js:105262:11)
    at Object.throwErr (http://www.lvh.me/__cypress/runner/cypress_runner.js:105217:18)
    at Object.throwErrByPath (http://www.lvh.me/__cypress/runner/cypress_runner.js:105249:17)
    at Object.retry (http://www.lvh.me/__cypress/runner/cypress_runner.js:96526:16)
    at checkForXhr (http://www.lvh.me/__cypress/runner/cypress_runner.js:92939:17)
    at http://www.lvh.me/__cypress/runner/cypress_runner.js:92940:28
    at tryCatcher (http://www.lvh.me/__cypress/runner/cypress_runner.js:139407:23)
    at Function.Promise.attempt.Promise.try (http://www.lvh.me/__cypress/runner/cypress_runner.js:136682:29)
    at tryFn (http://www.lvh.me/__cypress/runner/cypress_runner.js:96984:21)
    at whenStable (http://www.lvh.me/__cypress/runner/cypress_runner.js:97019:12)
    at http://www.lvh.me/__cypress/runner/cypress_runner.js:96569:16
    at tryCatcher (http://www.lvh.me/__cypress/runner/cypress_runner.js:139407:23)
    at Promise._settlePromiseFromHandler (http://www.lvh.me/__cypress/runner/cypress_runner.js:137343:31)
    at Promise._settlePromise (http://www.lvh.me/__cypress/runner/cypress_runner.js:137400:18)
    at Promise._settlePromise0 (http://www.lvh.me/__cypress/runner/cypress_runner.js:137445:10)
    at Promise._settlePromises (http://www.lvh.me/__cypress/runner/cypress_runner.js:137524:18)]]></failure>
    </testcase>
    <testcase name="Ask Question Community in laptop should leave an answer" time="0" classname="should leave an answer">
      <failure message="Timed out retrying: cy.wait() timed out waiting 30000ms for the 1st response to the route: &apos;postUuidActions&apos;. No response ever occurred." type="CypressError"><![CDATA[CypressError: Timed out retrying: cy.wait() timed out waiting 30000ms for the 1st response to the route: 'postUuidActions'. No response ever occurred.
    at Object.cypressErr (http://www.lvh.me/__cypress/runner/cypress_runner.js:105262:11)
    at Object.throwErr (http://www.lvh.me/__cypress/runner/cypress_runner.js:105217:18)
    at Object.throwErrByPath (http://www.lvh.me/__cypress/runner/cypress_runner.js:105249:17)
    at Object.retry (http://www.lvh.me/__cypress/runner/cypress_runner.js:96526:16)
    at checkForXhr (http://www.lvh.me/__cypress/runner/cypress_runner.js:92939:17)
    at http://www.lvh.me/__cypress/runner/cypress_runner.js:92940:28
    at tryCatcher (http://www.lvh.me/__cypress/runner/cypress_runner.js:139407:23)
    at Function.Promise.attempt.Promise.try (http://www.lvh.me/__cypress/runner/cypress_runner.js:136682:29)
    at tryFn (http://www.lvh.me/__cypress/runner/cypress_runner.js:96984:21)
    at whenStable (http://www.lvh.me/__cypress/runner/cypress_runner.js:97019:12)
    at http://www.lvh.me/__cypress/runner/cypress_runner.js:96569:16
    at tryCatcher (http://www.lvh.me/__cypress/runner/cypress_runner.js:139407:23)
    at Promise._settlePromiseFromHandler (http://www.lvh.me/__cypress/runner/cypress_runner.js:137343:31)
    at Promise._settlePromise (http://www.lvh.me/__cypress/runner/cypress_runner.js:137400:18)
    at Promise._settlePromise0 (http://www.lvh.me/__cypress/runner/cypress_runner.js:137445:10)
    at Promise._settlePromises (http://www.lvh.me/__cypress/runner/cypress_runner.js:137524:18)]]></failure>
    </testcase>
  </testsuite>
</testsuites>